/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_virtualinstrument_DetectionBasedTracker */

#ifndef _Included_com_example_administrator_virtualinstrument_DetectionBasedTracker
#define _Included_com_example_administrator_virtualinstrument_DetectionBasedTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_virtualinstrument_DetectionBasedTracker
 * Method:    nativeReturnXYCoordibate
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_administrator_virtualinstrument_DetectionBasedTracker_nativeReturnXYCoordibate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_administrator_virtualinstrument_DetectionBasedTracker
 * Method:    nativeChangeColor
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_administrator_virtualinstrument_DetectionBasedTracker_nativeChangeColor
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
